---
output: github_document
---

```{r, echo = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>",
  fig.path = "README-"
)
```

# klgo_bio_monitoring

This repository contains the data and code for our paper:

Reynolds, Joel H., Ward, Madeleine (20XX). _An assessment of the Coastal Waterbird monitoring project at Klondike Goldrush National Historical Park_. Name of journal/book <https://doi.org/xxx/xxx>

Our pre-print is online here:

Reynolds, Joel H., Ward, Madeleine (20XX). _An assessment of the Coastal Waterbird monitoring project at Klondike Goldrush National Historical Park_. Name of journal/book, Accessed `r format(Sys.Date(), "%d %b %Y")`. Online at <https://doi.org/xxx/xxx>


### How to cite

Please cite this compendium as:

Reynolds, Joel H., Ward, Madeleine (`r format(Sys.Date(), "%Y")`). _Compendium of R code and data for 'An assessment of the Coastal Waterbird monitoring project at Klondike Goldrush National Historical Park'_. Accessed `r format(Sys.Date(), "%d %b %Y")`. Online at <https://doi.org/xxx/xxx>

### How to download or install

You can download the compendium as a zip from from this URL: </archive/master.zip>

Or you can install this compendium as an R package, klgo_bio_monitoring, from GitHub with:
### Licenses

**Text and figures :**  [CC-BY-4.0](http://creativecommons.org/licenses/by/4.0/)

**Code :** See the [DESCRIPTION](DESCRIPTION) file

**Data :** [CC-0](http://creativecommons.org/publicdomain/zero/1.0/) attribution requested in reuse

### Contributions

We welcome contributions from everyone. Before you get started, please see our [contributor guidelines](CONTRIBUTING.md). Please note that this project is released with a [Contributor Code of Conduct](CONDUCT.md). By participating in this project you agree to abide by its terms.

